sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
- PACKAGES="django>=1.7,<1.8 django-mptt<0.8 django-polymorphic<1.3"
- PACKAGES="django>=1.8,<1.9"
- PACKAGES="django>=1.9,<1.10"
- PACKAGES="django>=1.10,<1.11"
matrix:
  exclude:
  - python: '3.3'
    env: PACKAGES="django>=1.9,<1.10"
  - python: '3.3'
    env: PACKAGES="django>=1.10,<1.11"
  - python: '3.5'
    env: PACKAGES="django>=1.7,<1.8 django-mptt<0.8 django-polymorphic<1.3"
  - python: '3.6'
    env: PACKAGES="django>=1.7,<1.8 django-mptt<0.8 django-polymorphic<1.3"
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- pip install $PACKAGES -e .
script:
- coverage run --source=polymorphic_tree runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: WWNa4MHf50AOybB+XW9UKXCk/9Q8r++Jc4xTdEib43rj4odH9wxIaTRrzAbbpo3EO2gYuLgq6mMbaIZPD5l2UmgSnyuIbeYAAKIQblT+8XMamtXwnSS5j9vfBXYdj54rTlh+jKwEMW/JiQKl+SQpfQ2v1NMvYO63m89Ev9vXvcU=
    on_success: never
    on_failure: always
